### ISSUE TITLE
question about light estimation

### ISSUE THREAD

**Issue by Lingyun0109** [half-potato/nmf#24]
Hello, I saw that the results of lighting estimation in your paper are excellent, even performing well in diffuse scenes like the teapot. I am working on lighting recovery myself, and when dealing with scenes like the teapot, I always find it difficult to correctly recover the lighting when using high-resolution pixel-based representations. Could I ask for your opinion on what you think is the key to correctly recovering the lighting for diffuse objects? _(:з」∠)_

**Comment by half-potato** [comment]
Hi, sorry for the delay. The teapot is not actually diffuse, which is why it is possible to recover the lighting. It has a glint, and is quite smooth. In fact, I believe this glint could be helpful in general for recovering lighting. It does not seem that purely diffuse objects actually exist much in practice.
